version: '3.1'

services:
  hermes:
    image: 'hermes'
    build: .
    container_name: 'hermes'
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /root/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hermes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: 'postgres:14'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres